package au.org.emii.portal.servlet;
// Generated Dec 17, 2009 1:45:03 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigInteger;

/**
 * WorldDepth generated by hbm2java
 */
public class WorldDepth  implements java.io.Serializable {


     private long id;
     private Double longitude;
     private Double latitude;
     private int depth;
     private Serializable geom;

    public WorldDepth() {
    }

	
    public WorldDepth(long id) {
        this.id = id;
    }
    public WorldDepth(long id, Double longitude, Double latitude, int depth, Serializable geom) {
       this.id = id;
       this.longitude = longitude;
       this.latitude = latitude;
       this.depth = depth;
       this.geom = geom;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public int getDepth() {
        return this.depth;
    }
    
    public void setDepth(int depth) {
        this.depth = depth;
    }
    public Serializable getGeom() {
        return this.geom;
    }
    
    public void setGeom(Serializable geom) {
        this.geom = geom;
    }




}


