/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package au.org.emii.portal.config;

import au.org.emii.portal.session.PortalSession;

import java.util.Properties;

/**
 * @author geoff
 */
public interface ConfigurationLoaderStage2 {

    /**
     * Get the current working portal session that is currently under
     * construction, as generated by the load() method
     *
     * @return
     */
    public PortalSession getWorkingPortalSession();

    /**
     * Set the master portal session that is currently under construction that
     * will be populated by the load() method.
     * <p/>
     * Not currently used and the existing stage2 implementation will overwrite
     * any instance set via this method.  The setter has only been created to
     * allow possible novel uses in the future
     *
     * @param portalSession
     */
    public void setWorkingPortalSession(PortalSession portalSession);


    /**
     * Check whether an error occurred while reloading
     *
     * @return
     */
    public boolean isError();

    /**
     * Check whether the portal is currently reloading
     *
     * @return
     */
    public boolean isReloading();

    public PortalSession load();

    /**
     * Cleanup any resources we are holding (portal document and portal session)
     */
    public void cleanup();

    void setProperties(Properties portalDocument);
}
