sudo: false
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
before_install:
  - mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
script:
  -  "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && mvn deploy || mvn install"
env:
  global:
  - secure: A56eDgiI+1SGUjLvXILSPHG2khX8xeGPDr/+/RiBJtaO4AelgZCKvJw4IUELvI8lP4C/0DzrtpC++w+Kiug3NzUUUw315sd77qzUEN4FYasJ9WjdhKOjTc1C23QoWXrEZBg9PO+aRFB9poDvb5WrrOWT8cvV1qocyG5OpIbPyQQ=
  - secure: hTMSY6RdQ3eFU3UdATHd+wQBymoBJwx7ioGnpNut6T0q6dtjPnt77MJ+TDNEjWe1xKzA/rnd2UBmE2L6CWe5orb53dihqwtreRLlpkNHeejdzDHsK7wU+vqYj0PIAuJaa/powsJhjoorUwyZf84WYH2/9xjxpTxKKPwihyaij10=
