ALTER TABLE layers ADD COLUMN keywords character varying(255);

update spatialdb.layers set keywords='reserve, coral, conservation' where id=900;
update spatialdb.layers set keywords='coral' where id=917;
update spatialdb.layers set keywords='IUCN, reserve, park, conservation' where id=896;
update spatialdb.layers set keywords='reserve, water, bird' where id=901;
update spatialdb.layers set keywords='bioregion, ecoregion, system' where id=20;
update spatialdb.layers set keywords='bioregion, ecoregion, system' where id=914;
update spatialdb.layers set keywords='bioregion, ecoregion, system, marine' where id=21;
update spatialdb.layers set keywords='adminisration, government, landcare, heritage, local' where id=916;
update spatialdb.layers set keywords='reserve, water, bird' where id=915;
update spatialdb.layers set keywords='farm, SLA, cereal, manage' where id=612;
update spatialdb.layers set keywords='farm, SLA, cereal, manage' where id=604;
update spatialdb.layers set keywords='farm, SLA, water, manage' where id=613;
update spatialdb.layers set keywords='farm, cereal, SLA, manage' where id=614;
update spatialdb.layers set keywords='farm, cereal, SLA, manage' where id=605;
update spatialdb.layers set keywords='farm, cereal, SLA, manage' where id=611;
update spatialdb.layers set keywords='farm, cereal, SLA, manage' where id=606;
update spatialdb.layers set keywords='GER, IBRA, ecoregion, bioregion' where id=902;
update spatialdb.layers set keywords='GER, administrate, manage' where id=903;
update spatialdb.layers set keywords='GER, manage, adminstrate, region, border, coast, hunter, Kosciuszko, slope, summit' where id=904;
update spatialdb.layers set keywords='GER, administrative, manage' where id=905;
update spatialdb.layers set keywords='GER, administrative, manage, region' where id=906;
update spatialdb.layers set keywords='GER, administrative, manage, region' where id=907;
update spatialdb.layers set keywords='GER, manage, adminstrate, region, border, coast, hunter, Kosciuszko, slope, summit, region' where id=908;
update spatialdb.layers set keywords='GER, region, administrate, region' where id=909;
update spatialdb.layers set keywords='GER, slope, summit, region' where id=910;
update spatialdb.layers set keywords='GER, slope, summit, manage, region' where id=911;
update spatialdb.layers set keywords='GER, slope, summit, manage, region' where id=912;
update spatialdb.layers set keywords='GER, region' where id=913;
update spatialdb.layers set keywords='landuse, manage' where id=678;
update spatialdb.layers set keywords='region, funds' where id=591;
update spatialdb.layers set keywords='threatened, bird' where id=682;
update spatialdb.layers set keywords='average, sample' where id=898;
update spatialdb.layers set keywords='diversity, occurrence, sample, average' where id=899;
update spatialdb.layers set keywords='endangered, vulnerable, critical' where id=681;
update spatialdb.layers set keywords='water, temperature, precipitation, rain' where id=747;
update spatialdb.layers set keywords='water, temperature, precipitation, rain' where id=668;
update spatialdb.layers set keywords='water, temperature, precipitation, rain' where id=767;
update spatialdb.layers set keywords='water, temperature, precipitation, rain' where id=720;
update spatialdb.layers set keywords='water, temperature, precipitation, rain' where id=671;
update spatialdb.layers set keywords='water, temperature, precipitation, rain, capacity' where id=722;
update spatialdb.layers set keywords='water, temperature, precipitation, rain, capacity' where id=731;
update spatialdb.layers set keywords='water, temperature, precipitation, rain, capacity' where id=751;
update spatialdb.layers set keywords='temperature, moisture' where id=728;
update spatialdb.layers set keywords='temperature, moisture' where id=746;
update spatialdb.layers set keywords='temperature, moisture' where id=743;
update spatialdb.layers set keywords='temperature, moisture' where id=742;
update spatialdb.layers set keywords='temperature, moisture' where id=749;
update spatialdb.layers set keywords='temperature, moisture' where id=744;
update spatialdb.layers set keywords='temperature, moisture' where id=738;
update spatialdb.layers set keywords='temperature, moisture' where id=757;
update spatialdb.layers set keywords='temperature, moisture' where id=733;
update spatialdb.layers set keywords='temperature, moisture' where id=732;
update spatialdb.layers set keywords='temperature, moisture' where id=724;
update spatialdb.layers set keywords='temperature, moisture' where id=735;
update spatialdb.layers set keywords='evaporation, rain, precipitation, temperature' where id=715;
update spatialdb.layers set keywords='evaporation, rain, precipitation, temperature' where id=719;
update spatialdb.layers set keywords='evaporation, rain, precipitation, temperature' where id=765;
update spatialdb.layers set keywords='rain' where id=598;
update spatialdb.layers set keywords='rain' where id=893;
update spatialdb.layers set keywords='rain' where id=734;
update spatialdb.layers set keywords='rain' where id=713;
update spatialdb.layers set keywords='rain' where id=772;
update spatialdb.layers set keywords='rain' where id=745;
update spatialdb.layers set keywords='rain' where id=594;
update spatialdb.layers set keywords='rain' where id=600;
update spatialdb.layers set keywords='rain' where id=863;
update spatialdb.layers set keywords='rain' where id=726;
update spatialdb.layers set keywords='rain' where id=872;
update spatialdb.layers set keywords='rain' where id=889;
update spatialdb.layers set keywords='rain' where id=718;
update spatialdb.layers set keywords='rain' where id=779;
update spatialdb.layers set keywords='rain' where id=754;
update spatialdb.layers set keywords='rain' where id=882;
update spatialdb.layers set keywords='rain' where id=750;
update spatialdb.layers set keywords='rain' where id=602;
update spatialdb.layers set keywords='rain' where id=758;
update spatialdb.layers set keywords='rain' where id=766;
update spatialdb.layers set keywords='rain' where id=593;
update spatialdb.layers set keywords='rain' where id=601;
update spatialdb.layers set keywords='rain' where id=764;
update spatialdb.layers set keywords='rain' where id=778;
update spatialdb.layers set keywords='rain' where id=595;
update spatialdb.layers set keywords='rain' where id=878;
update spatialdb.layers set keywords='rain' where id=711;
update spatialdb.layers set keywords='rain' where id=866;
update spatialdb.layers set keywords='rain' where id=886;
update spatialdb.layers set keywords='rain' where id=596;
update spatialdb.layers set keywords='rain' where id=599;
update spatialdb.layers set keywords='rain' where id=740;
update spatialdb.layers set keywords='rain' where id=712;
update spatialdb.layers set keywords='rain' where id=763;
update spatialdb.layers set keywords='rain' where id=788;
update spatialdb.layers set keywords='rain' where id=786;
update spatialdb.layers set keywords='rain' where id=791;
update spatialdb.layers set keywords='rain' where id=782;
update spatialdb.layers set keywords='rain' where id=794;
update spatialdb.layers set keywords='rain' where id=797;
update spatialdb.layers set keywords='rain' where id=798;
update spatialdb.layers set keywords='rain' where id=796;
update spatialdb.layers set keywords='solar, sun' where id=881;
update spatialdb.layers set keywords='solar, sun' where id=869;
update spatialdb.layers set keywords='solar, sun' where id=861;
update spatialdb.layers set keywords='solar, sun' where id=880;
update spatialdb.layers set keywords='solar, sun' where id=871;
update spatialdb.layers set keywords='solar, sun' where id=768;
update spatialdb.layers set keywords='solar, sun' where id=770;
update spatialdb.layers set keywords='solar, sun' where id=887;
update spatialdb.layers set keywords='solar, sun' where id=894;
update spatialdb.layers set keywords='solar, sun' where id=877;
update spatialdb.layers set keywords='day, daily, season, ratio' where id=883;
update spatialdb.layers set keywords='variation, mean, ratio' where id=892;
update spatialdb.layers set keywords='rain, precipitation' where id=870;
update spatialdb.layers set keywords='day, daily, max, ratio' where id=785;
update spatialdb.layers set keywords='precipitation, rain' where id=799;
update spatialdb.layers set keywords='diurnal, day, daily, season, ratio' where id=790;
update spatialdb.layers set keywords='range, mean, ratio' where id=783;
update spatialdb.layers set keywords='rain, precipitation' where id=784;
update spatialdb.layers set keywords='speed, distance' where id=860;
update spatialdb.layers set keywords='speed, distance' where id=854;
update spatialdb.layers set keywords='speed, distance' where id=857;
update spatialdb.layers set keywords='population, infrastructure, towns, service' where id=647;
update spatialdb.layers set keywords='water, runoff' where id=670;
update spatialdb.layers set keywords='water, runoff' where id=666;
update spatialdb.layers set keywords='water, runoff' where id=672;
update spatialdb.layers set keywords='CARS, marine' where id=802;
update spatialdb.layers set keywords='CARS, marine' where id=803;
update spatialdb.layers set keywords='CARS, marine' where id=804;
update spatialdb.layers set keywords='CARS, marine' where id=801;
update spatialdb.layers set keywords='CARS, marine' where id=800;
update spatialdb.layers set keywords='CARS, marine' where id=805;
update spatialdb.layers set keywords='nation, state, political' where id=922;
update spatialdb.layers set keywords='political' where id=22;
update spatialdb.layers set keywords='local, government, area, administate, region, state, territory' where id=23;
update spatialdb.layers set keywords='lithology, rock, outcrop, unit, stratigraph' where id=923;
update spatialdb.layers set keywords='soil, calcium, lithology' where id=829;
update spatialdb.layers set keywords='soil, primary, productivity, NPP' where id=837;
update spatialdb.layers set keywords='nutrient, soil, rock' where id=838;
update spatialdb.layers set keywords='soil, nutrient' where id=831;
update spatialdb.layers set keywords='soil, nutrient' where id=821;
update spatialdb.layers set keywords='soil, nutrient' where id=822;
update spatialdb.layers set keywords='soil, fertility, nitrogen, phosphorus, potassium' where id=843;
update spatialdb.layers set keywords='soil, fertility' where id=811;
update spatialdb.layers set keywords='soil, fertility' where id=828;
update spatialdb.layers set keywords='soil, fertility' where id=817;
update spatialdb.layers set keywords='soil,  sodium, water' where id=664;
update spatialdb.layers set keywords='evaporation, water, temperature' where id=755;
update spatialdb.layers set keywords='evaporation, water, temperature' where id=736;
update spatialdb.layers set keywords='evaporation, water, temperature' where id=771;
update spatialdb.layers set keywords='soil, permiability, saturation' where id=833;
update spatialdb.layers set keywords='soil, permiability, saturation' where id=842;
update spatialdb.layers set keywords='soil, water, saturation' where id=669;
update spatialdb.layers set keywords='soil, water, saturation' where id=667;
update spatialdb.layers set keywords='soil, water, saturation' where id=891;
update spatialdb.layers set keywords='soil, water, saturation' where id=873;
update spatialdb.layers set keywords='soil, water, saturation' where id=884;
update spatialdb.layers set keywords='soil, water, saturation' where id=865;
update spatialdb.layers set keywords='soil, water, saturation' where id=895;
update spatialdb.layers set keywords='soil, water, saturation' where id=864;
update spatialdb.layers set keywords='soil, water, saturation' where id=885;
update spatialdb.layers set keywords='soil, water, saturation, temperature' where id=868;
update spatialdb.layers set keywords='soil, structure, water' where id=825;
update spatialdb.layers set keywords='soil, slope, water' where id=826;
update spatialdb.layers set keywords='soil, capacity, water' where id=818;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=714;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=706;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=727;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=662;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=812;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=717;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=723;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=721;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=708;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=748;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=709;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=773;
update spatialdb.layers set keywords='soil, evaporation, temperature, rain, precipitation' where id=777;
update spatialdb.layers set keywords='soil, structure, porosity' where id=806;
update spatialdb.layers set keywords='soil, grain' where id=814;
update spatialdb.layers set keywords='erosion, stability, slope, friability' where id=661;
update spatialdb.layers set keywords='erosion, stability, slope, friability' where id=823;
update spatialdb.layers set keywords='erosion, stability, slope, friability' where id=597;
update spatialdb.layers set keywords='soil, horizon' where id=816;
update spatialdb.layers set keywords='soil, structure, porosity, grain' where id=841;
update spatialdb.layers set keywords='soil, grain' where id=845;
update spatialdb.layers set keywords='angle, direction' where id=680;
update spatialdb.layers set keywords='depth' where id=848;
update spatialdb.layers set keywords='height' where id=674;
update spatialdb.layers set keywords='elevation, height, difference' where id=827;
update spatialdb.layers set keywords='elevation, height, difference' where id=844;
update spatialdb.layers set keywords='angle' where id=836;
