#!/bin/bash

# This script generates an endemism layer using data generated by the biocache and loads it into the spatial portal

GEOSERVER_USRPWD="user:password"
GEOSERVER_URL="http://localhost:8082/geoserver"
PTH="/data/ala/data/layers"
GDAL_TRANSLATE="/data/ala/utils/gdal-1.9.0/apps/gdal_translate"

# download generated data from the biocache
echo "downloading data from biocache"
wget http://biocache.ala.org.au/archives/exports/cell-species-lists-0.1-degree.txt
wget http://biocache.ala.org.au/archives/exports/species-cell-counts-0.1-degree.txt

# generate ASCII grid and DIVA grid
echo "generating grid files"
java -Xmx3G -cp alaspatial/WEB-INF/classes/.:alaspatial/WEB-INF/lib/* org.ala.spatial.analysis.layers.Endemism 0.1 species-cell-counts-0.1-degree.txt cell-species-lists-0.1-degree.txt . testendemism

cp testendemism.gr* $PTH/ready/diva

# Generate geotiff
echo "generating geotiff"
$GDAL_TRANSLATE -of GTiff -ot Float32 -a_srs EPSG:4326 testendemism.asc testendemism.tif
cp testendemism.tif $PTH/ready/geotiff

# Generate legend
echo "generating legend"
java -Xmx3G -cp "./alaspatial/WEB-INF/lib/*" org.ala.layers.legend.GridLegend $PTH/ready/diva/testendemism $PTH/test/testendemism 8 1

# Upload to geoserver
echo "uploading to geoserver"
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/plain"  -d "file://$PTH/ready/geotiff/testendemism.tif" $GEOSERVER_URL/rest/workspaces/ALA/coveragestores/testendemism/external.geotiff
#curl -u $GEOSERVER_USRPWD -XPOST -H "Content-type: text/xml"  -d "<style><name>testendemism_style</name><filename>srichness.sld</filename></style>"  $GEOSERVER_URL/rest/styles
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: application/vnd.ogc.sld+xml"  -d @$PTH/test/testendemism.sld $GEOSERVER_URL/rest/styles/testendemism_style
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/xml"   -d "<layer><enabled>true</enabled><defaultStyle><name>testendemism_style</name></defaultStyle></layer>" $GEOSERVER_URL/rest/layers/ALA:testendemism
