#!/bin/bash

# This script generates an endemism layer using data generated by the biocache and loads it into the spatial portal

DATE=$(date +built_%y%m%d)
JAVA_CLASSPATH="./layer-ingestion-1.0-SNAPSHOT/layer-ingestion-1.0-SNAPSHOT.jar:./layer-ingestion-1.0-SNAPSHOT/lib/*"
GEOSERVER_USRPWD="user:password"
GEOSERVER_URL="http://localhost:8082/geoserver"
PTH="/data/ala/data/layers"
OUTPUTDIR="$PTH/process/endemism/$DATE"
GDAL_TRANSLATE="/data/ala/utils/gdal-1.9.0/apps/gdal_translate"

# Create directory to store output files:
mkdir $OUTPUTDIR

# download generated data from the biocache
echo "downloading data from biocache"
wget http://biocache.ala.org.au/archives/exports/cell-species-lists-0.1-degree.txt
wget http://biocache.ala.org.au/archives/exports/species-cell-counts-0.1-degree.txt
wget http://biocache.ala.org.au/archives/exports/cell-species-lists-0.1-degree-non-marine.txt
wget http://biocache.ala.org.au/archives/exports/species-cell-counts-0.1-degree-non-marine.txt
mv *.txt $OUTPUTDIR

# generate ASCII grid and DIVA grid
echo "generating grid files"
java -Xmx3G -cp ${JAVA_CLASSPATH} org.ala.spatial.analysis.layers.Endemism 0.1 $OUTPUTDIR/species-cell-counts-0.1-degree.txt $OUTPUTDIR/cell-species-lists-0.1-degree.txt $OUTPUTDIR endemism
java -Xmx3G -cp ${JAVA_CLASSPATH} org.ala.spatial.analysis.layers.Endemism 0.1 $OUTPUTDIR/species-cell-counts-0.1-degree-non-marine.txt $OUTPUTDIR/cell-species-lists-0.1-degree-non-marine.txt $OUTPUTDIR endemism_non_marine

cp $OUTPUTDIR/endemism.gr* $PTH/ready/diva
cp $OUTPUTDIR/endemism_non_marine.gr* $PTH/ready/diva

# Generate geotiff
echo "generating geotiff"
$GDAL_TRANSLATE -of GTiff -ot Float32 -a_srs EPSG:4326 $OUTPUTDIR/endemism.asc $OUTPUTDIR/endemism.tif
cp $OUTPUTDIR/endemism.tif $PTH/ready/geotiff
$GDAL_TRANSLATE -of GTiff -ot Float32 -a_srs EPSG:4326 $OUTPUTDIR/endemism_non_marine.asc $OUTPUTDIR/endemism_non_marine.tif
cp $OUTPUTDIR/endemism_non_marine.tif $PTH/ready/geotiff

# Generate legend
echo "generating legend"
java -Xmx3G -cp ${JAVA_CLASSPATH} org.ala.layers.legend.GridLegend $PTH/ready/diva/endemism $PTH/test/endemism 8 1
java -Xmx3G -cp ${JAVA_CLASSPATH} org.ala.layers.legend.GridLegend $PTH/ready/diva/endemism_non_marine $PTH/test/endemism_non_marine 8 1

# Upload to geoserver
echo "uploading to geoserver"
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/plain"  -d "file://$PTH/ready/geotiff/endemism.tif" $GEOSERVER_URL/rest/workspaces/ALA/coveragestores/endemism/external.geotiff
curl -u $GEOSERVER_USRPWD -XPOST -H "Content-type: text/xml"  -d "<style><name>endemism_style</name><filename>endemism.sld</filename></style>"  $GEOSERVER_URL/rest/styles
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: application/vnd.ogc.sld+xml"  -d @$PTH/test/endemism.sld $GEOSERVER_URL/rest/styles/endemism_style
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/xml"   -d "<layer><enabled>true</enabled><defaultStyle><name>endemism_style</name></defaultStyle></layer>" $GEOSERVER_URL/rest/layers/ALA:endemism

curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/plain"  -d "file://$PTH/ready/geotiff/endemism_non_marine.tif" $GEOSERVER_URL/rest/workspaces/ALA/coveragestores/endemism_non_marine/external.geotiff
curl -u $GEOSERVER_USRPWD -XPOST -H "Content-type: text/xml"  -d "<style><name>endemism_non_marine_style</name><filename>endemism_non_marine.sld</filename></style>"  $GEOSERVER_URL/rest/styles
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: application/vnd.ogc.sld+xml"  -d @$PTH/test/endemism_non_marine.sld $GEOSERVER_URL/rest/styles/endemism-non-marne_style
curl -u $GEOSERVER_USRPWD -XPUT -H "Content-type: text/xml"   -d "<layer><enabled>true</enabled><defaultStyle><name>endemism_non_marine_style</name></defaultStyle></layer>" $GEOSERVER_URL/rest/layers/ALA:endemism_non_marine

# Regenerate layer analysis and distances
echo "regenerating layer analysis and distances"
rm -f /data/ala/data/layers/analysis/0.5/el1055.gr*
rm -f /data/ala/data/layers/analysis/0.5/el1056.gr*
rm -f /data/ala/data/layers/analysis/0.01/el1055.gr*
rm -f /data/ala/data/layers/analysis/0.01/el1056.gr*
rm -f /data/ala/data/layers/analysis/0.0025/el1055.gr*
rm -f /data/ala/data/layers/analysis/0.0025/el1056.gr*
cp /data/ala/data/alaspatial/layerDistances.properties /data/ala/data/alaspatial/layerDistances.properties_old
sed -i '/el1055\|el1056/d' /data/ala/data/alaspatial/layerDistances.properties

./layer-ingestion-1.0-SNAPSHOT/environmental_background_processing.sh 

